### ISSUE TITLE
rift: not enough arguments in call to WalkAction

### ISSUE THREAD

**Issue by mewmew** [sean-brock/rift#2]
When trying to go-get this project, I get the following error:

This is on rev 4ade9599358b1e5743a4f7d71e51c2174a45a0a5.

```
# github.com/sean-brock/rift
goget/src/github.com/sean-brock/rift/main.go:40:25: not enough arguments in call to WalkAction
	have ()
	want (*Actor, int, int)
```

**Comment by sean-brock** [comment]
It's expected. I'm just testing some different graphics libraries right now. Itll get cleaned up soon.

**Comment by sean-brock** [comment]
Ramen/Ebiten example should work now.

**Comment by mewmew** [comment]
It does! Thanks for the fix.

![2018-10-30-225703_550x330_scrot](https://user-images.githubusercontent.com/1414531/47753245-27297180-dc97-11e8-9a46-11fce664dfc2.png)
